cad/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("dispatch.urls"))
]

dispatch/urls.py
from django.urls import path

from . import views

app_name = "dispatch"
urlpatterns = [
    path("", views.CallsListView.as_view(), name="view_calls"),
    # path("view-call/<int:pk>/", views.CallDetailView.as_view(), name="call_details"),
    
    path("call/add/", views.CallCreateView.as_view(), name="call_add"),
    path("call/<int:pk>/", views.CallUpdateView.as_view(), name="call_update"),
    path("call/<int:pk>/delete", views.CallDeleteView.as_view(), name="call_delete"),
    
    path("closed-calls/", views.closed_calls, name="closed_calls"),
    path("shift/", views.shift, name="shift"),
    path("not-implemented/", views.not_implemented, name="not_implemented"),
]

dispatch/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.contrib import admin

# Create your models here.

class Officer(models.Model):
    first_name = models.CharField(max_length=32)
    last_name = models.CharField(max_length=32)
    radio_id = models.CharField(max_length=32)
    active_call = models.ForeignKey(
            "Call",
            on_delete=models.SET_NULL,
            null=True,
            blank=True,
    )
    vehicle = models.OneToOneField(
            "Vehicle", 
            on_delete=models.SET_NULL,
            null=True,
            blank=True,
    )   

    @admin.display(
            ordering="radio_id",
    )

    def get_name(self):
        name_string = "{}. {}"
        return name_string.format(self.first_name[0], self.last_name)

    def __str__(self):
        name_string = "{} ({})"
        return name_string.format( self.get_name(), self.radio_id )

class Vehicle(models.Model):
    verbal_name = models.CharField(max_length=32, verbose_name="Vehicle")
    variety = models.CharField(max_length=32, verbose_name="Model")
    radio_id = models.CharField(max_length=4, verbose_name="Vehicle ID")
    license_plate = models.OneToOneField(
        "LicensePlate",
        on_delete=models.CASCADE,
        verbose_name="License Plate",
    )

    def __str__(self):
        return self.radio_id

class LicensePlate(models.Model):
    MUNICIPAL_VEHICLE="MVN"
    MUNICIPAL_MOTORCYCLE="MXN"
    PASSENGER_NORMAL="PAN"

    PLATE_TYPE_CHOICES = [
        (
            "Municipal",
            (
                (MUNICIPAL_VEHICLE, "Municipal Vehicle"),
                (MUNICIPAL_MOTORCYCLE, "Municipal Motorcycle"),
            ),
        ),
        (
            "Passenger",
            (
                (PASSENGER_NORMAL, "Passenger Normal"),
            ),
        ),
        ("XXX", "Unknown"),
    ]

    plate_type = models.CharField(
            max_length=3,
            choices=PLATE_TYPE_CHOICES,
            default=MUNICIPAL_VEHICLE,
    )

    plate_number = models.CharField(max_length=8)

    def __str__(self):
        return self.plate_number

class Call(models.Model):
    name = models.CharField(max_length=64)
    active = models.BooleanField(default=True)
    notes = models.TextField(null=True)
    time_generated = models.DateTimeField(
            verbose_name="Created at",
            default=timezone.now,
    )
    
    def get_absolute_url(self):
        return reverse("dispatch:call_update", kwargs={"pk": self.pk})

    def __str__(self):
        return self.name

dispatch/forms.py
from django import forms
from .models import Call

class CallForm(forms.Form):
  call_name = forms.CharField(label="Call name", max_length=64)
  call_notes = forms.Textarea()

dispatch/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic
from django.views.generic.edit import CreateView, DeleteView, UpdateView


from .models import Call, Officer
from .forms import CallForm

# Create your views here.

class CallsListView(generic.ListView):
    paginate_by = 20
    context_object_name = "calls_list"
    template_name = "dispatch/view_calls.html"

    queryset = Call.objects.filter(active=True)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["home_nav"] = "active"
        return context

class CallCreateView(CreateView):
    model = Call
    fields = ["name"]
    template_name = "dispatch/call_create_form.html"
    

class CallUpdateView(UpdateView):
    model = Call
    fields = ["name", "active", "notes",]
    template_name = "dispatch/call_update_form.html"

class CallDeleteView(DeleteView):
    model = Call
    success_url = reverse_lazy("dispatch:view_calls")


# class CallFormView(generic.FormView):
#     template_name = "dispatch.call_details.html"
#     form_class = CallForm
#     success_url = "#"

class CallDetailView(generic.DetailView):
    model = Call
    template_name = "dispatch/call_details.html"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["calls_nav"] = "active"
        
        avofc = Officer.objects.filter(active_call=None)
        if (avofc.count() > 0):
            context["available_officers"] = avofc
        
        return context

def new_call(request):
    context = {"calls_nav":"active",
               "new_call_nav":"active",
               }
    return render(request, "dispatch/new_call.html", context)

def closed_calls(request):
    context = {"calls_nav":"active",
               "closed_calls_nav":"active",
               }
    return render(request, "dispatch/closed_calls.html", context)

def shift(request):
    context = {"shift_nav":"active"}
    return render(request, "dispatch/shift.html", context)

def not_implemented(request):
    context = {}
    return render(request, "dispatch/not_implemented.html", context)

dispatch/templates/dispatch/call_confirm_delete.html
{% extends "main.html" %}

{% block title %}Call Details{% endblock %}

{% block content %}
<h1>{{ call.name }}</h1>

<form method="POST" class="post-form">{% csrf_token %}
  {{ form.as_p }}
  <h2>Are you sure you want to delete this call?</h2>
  <button class="btn btn-danger save" type="submit">Delete</button>
  <a class="btn btn-secondary" href="{% url "dispatch:call_update" call.id %}">Cancel</a>
</form>


{% comment %} <h2>Officers Assigned</h2>
<div class="px-4">  
  <ul>
    {% for ofc in call.officer_set.all %}
        <li>{{ofc}}</li>
    {% endfor %}
  </ul>
  <div class="dropdown">
    <a class="btn btn-success dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">Assign Officer</a>
    <ul class="dropdown-menu">
      {% if available_officers %}
        {% for ofc in available_officers %}
          <li><a class="dropdown-item" href="#">{{ ofc }}</a></li>
        {% endfor %}
      {% else %}
        <li><a class="dropdown-item" href="#">No available officers</a></li>
      {% endif %}

    </ul>
  </div> {% endcomment %}

</div>
{% endblock %}

dispatch/templates/dispatch/call_create_form.html
{% extends "main.html" %}

{% block title %}Call Details{% endblock %}

{% block content %}
<h1>{{ call.name }}</h1>

<form method="POST" class="post-form">{% csrf_token %}
  {{ form.as_p }}
  <button class="btn btn-success" type="submit" class="save btn btn-default">Save</button>
</form>


{% comment %} <h2>Officers Assigned</h2>
<div class="px-4">  
  <ul>
    {% for ofc in call.officer_set.all %}
        <li>{{ofc}}</li>
    {% endfor %}
  </ul>
  <div class="dropdown">
    <a class="btn btn-success dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">Assign Officer</a>
    <ul class="dropdown-menu">
      {% if available_officers %}
        {% for ofc in available_officers %}
          <li><a class="dropdown-item" href="#">{{ ofc }}</a></li>
        {% endfor %}
      {% else %}
        <li><a class="dropdown-item" href="#">No available officers</a></li>
      {% endif %}

    </ul>
  </div> {% endcomment %}

</div>
{% endblock %}

dispatch/templates/dispatch/call_details.html
{% extends "main.html" %}

{% block title %}Call Details{% endblock %}

{% block content %}
<h1>{{ call.name }}</h1>
{% endblock %}

dispatch/templates/dispatch/call_update_form.html
{% extends "main.html" %}

{% block title %}Call Details{% endblock %}

{% block content %}
<h1>{{ call.name }}</h1>

<form method="POST" class="post-form">{% csrf_token %}
  {{ form.as_p }}
  <button class="btn btn-success" type="submit" class="save btn btn-default">Save</button>
  <a class="btn btn-danger" href="{% url "dispatch:call_delete" call.id %}">Delete</a>
</form>


{% comment %} <h2>Officers Assigned</h2>
<div class="px-4">  
  <ul>
    {% for ofc in call.officer_set.all %}
        <li>{{ofc}}</li>
    {% endfor %}
  </ul>
  <div class="dropdown">
    <a class="btn btn-success dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">Assign Officer</a>
    <ul class="dropdown-menu">
      {% if available_officers %}
        {% for ofc in available_officers %}
          <li><a class="dropdown-item" href="#">{{ ofc }}</a></li>
        {% endfor %}
      {% else %}
        <li><a class="dropdown-item" href="#">No available officers</a></li>
      {% endif %}

    </ul>
  </div> {% endcomment %}

</div>
{% endblock %}

dispatch/templates/dispatch/closed_calls.html
{% extends "main.html" %}

{% block title %}Closed Calls{% endblock %}

{% block content %}
<h1>TO BE IMPLEMENTED</h1>
{% endblock %}

dispatch/templates/dispatch/new_call.html
{% extends "main.html" %}

{% block title %}New Call{% endblock %}

{% block content %}
<h1>TO BE IMPLEMENTED</h1>
{% endblock %}

dispatch/templates/dispatch/not_implemented.html
{% extends "main.html" %}

{% block title %}NOT IMPLEMENTED{% endblock %}

{% block content %}
<h1>TO BE IMPLEMENTED</h1>
{% endblock %}

dispatch/templates/dispatch/shift.html
{% extends "main.html" %}

{% block title %}Shift{% endblock %}

{% block content %}
<h1>TO BE IMPLEMENTED</h1>
{% endblock %}

dispatch/templates/dispatch/view_calls.html
{% extends "main.html" %}

{% block title %}View Calls{% endblock %}

{% block content %}
<h1>Active Calls</h1>
  <table class="table table-striped align-middle">
    <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Call created at</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
    {% if calls_list %}
      {% for call in calls_list %}
        <tr>
          <td>{{call.name}}</td>
          <td>{{call.time_generated}}</td>
          <td><a href="{% url 'dispatch:call_update' call.id %}" class="btn btn-primary">View Call</a></td>
        </tr>
      {% endfor %}
    {% endif %}
    </tbody>
    <tfoot class="table-secondary">
      <tr>
        <td><a href="{% url 'dispatch:call_add' %}" class="btn btn-success">New Call</a></td>
        <td/>
        <td/>
      </tr>
    </tfoot>
  </table>

{% endblock %}

dispatch/templates/main.html
<!DOCTYPE html>
<html>
  <head>
    <title>{% block title %}{% endblock %}</title>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
  </head>

  <body>
      <div>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark bg-gradient px-2">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
        <div class="navbar-nav nav-pills nav-justified collapse navbar-collapse" id="navbarNav">
          <a class="nav-item nav-link {{home_nav}}" href="{% url 'dispatch:view_calls' %}">Home</a>
          <div class="nav-item dropdown">
            <a class="nav-link dropdown-toggle {{calls_nav}}" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">Calls</a>
            <ul class="dropdown-menu dropdown-menu-dark">
              <li><a class="dropdown-item {{new_call_nav}}" href="{% url 'dispatch:call_add' %}">New Call</a></li>
              <li><a class="dropdown-item {{closed_calls_nav}}" href="{% url 'dispatch:closed_calls' %}">Closed Calls</a></li>
            </ul>
          </div>
          <a class="nav-item nav-link {{shift_nav}}" href="{% url 'dispatch:shift' %}">Shift</a>
          {% if user.is_authenticated %}
            <a class="nav-item nav-link" href="{% url 'dispatch:not_implemented' %}?next={{ request.path }}">Logout ({{user.get_username}})</a></li>
            {% comment %} <a href="{% url 'registration:logout' %}?next={{ request.path }}">Logout</a></li> {% endcomment %}
          {% else %}
            <div class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">Login</a>

              <form class="dropdown-menu p-4">
                <div class="mb-3">
                  <label for="exampleDropdownFormEmail2" class="form-label">Email address</label>
                  <input type="email" class="form-control" id="exampleDropdownFormEmail2" placeholder="email@example.com">
                </div>
                <div class="mb-3">
                  <label for="exampleDropdownFormPassword2" class="form-label">Password</label>
                  <input type="password" class="form-control" id="exampleDropdownFormPassword2" placeholder="Password">
                </div>
                <div class="mb-3">
                  <div class="form-check">
                    <input type="checkbox" class="form-check-input" id="dropdownCheck2">
                    <label class="form-check-label" for="dropdownCheck2">
                      Remember me
                    </label>
                  </div>
                </div>
                <button type="submit" class="btn btn-primary">Sign in</button>
              </form>
            </div>
            {% comment %} <a class="nav-item nav-link" href="{% url 'dispatch:not_implemented' %}?next={{ request.path }}">Login</a></li> {% endcomment %}
            {% comment %} <a href="{% url 'registration:login' %}?next={{ request.path }}">Login</a></li> {% endcomment %}
          {% endif %}
        </div>                   
    </nav>

    <div class="container-lg">
    {% block content %}
    {% endblock %}
  </div>
  </body>
</html>